project_id = "jjhbgirxambbejienqey"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.create-ride]
verify_jwt = true

[functions.accept-ride]
verify_jwt = true