// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jjhbgirxambbejienqey.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpqaGJnaXJ4YW1iYmVqaWVucWV5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1NzUxMDksImV4cCI6MjA3MjE1MTEwOX0.75kIeHH-0spW7JYkJghDV7TyW2dp0cNi0vGRfqkXkgM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});